export const types = {
  LOGIN: "LOGIN",
  LOGIN_ERROR: "LOGIN_ERROR",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",

  SIGNUP: "SIGNUP",
  SIGNUP_ERROR: "SIGNUP_ERROR",
  SIGNUP_SUCCESS: "SIGNUP_SUCCESS",

  GET_SCREAMS: "GET_SCREAMS",
  GET_SCREAMS_SUCCESS: "GET_SCREAMS_SUCCESS",
  GET_SCREAMS_FALIURE: "GET_SCREAMS_FALIURE",

  GET_USER: "GET_USER",
  GET_USER_SUCCESS: "GET_USER_SUCCESS",
  GET_USER_FALIURE: "GET_USER_FALIURE",

  // USER reducer AUTH
  SET_AUTHENTICATED: "SET_AUTHENTICATED",
  SET_UNAUTHENTICATED: "SET_UNAUTHENTICATED",
  SET_USER: "SET_USER",
  LOADING_USER: "LOADING_USER",
  USER_LOGOUT: "USER_LOGOUT",

  EDIT_USER_DETAILS: "EDIT_USER_DETAILS",
  EDIT_USER_DETAILS_REQUEST: "EDIT_USER_DETAILS_REQUEST",
  EDIT_USER_DETAILS_SUCCESS: "EDIT_USER_DETAILS_SUCCESS",
  EDIT_USER_DETAILS_FAILURE: "EDIT_USER_DETAILS_FAILURE",

  // SCREAM
  LIKE_SCREAM: "LIKE_SCREAM",
  LIKE_SCREAM_SUCCESS: "LIKE_SCREAM_SUCCESS",
  UNLIKE_SCREAM: "UNLIKE_SCREAM",
  UNLIKE_SCREAM_SUCCESS: "UNLIKE_SCREAM_SUCCESS",

  DELETE_SCREAM: "DELETE_SCREAM",
  DELETE_SCREAM_SUCCESS: "DELETE_SCREAM_SUCCESS",
  DELETE_SCREAM_FAIL: "DELETE_SCREAM_FAIL",

  // UI
  SET_ERRORS: "SET_ERROR",
  LOADING_UI: "LOADING_UI",
  LOADING_DATA: "LOADING_DATA",
  LOADING_DATA_COMPLETED: "LOADING_DATA_COMPLETED",
  CLEAR_ERRORS: "CLEAR_ERRORS",

  UPLOAD_IMAGE: "UPLOAD_IMAGE",
  UPLOAD_IMAGE_SUCCESS: "UPLOAD_IMAGE_SUCCESS",
  UPLOAD_IMAGE_FALIURE: "UPLOAD_IMAGE_FALIURE"
};
